/** Minecraft version identifier used to select the source assets. */
export type MinecraftVersion = string;

/** Styles generated by BlockFont. */
export type FontStyle = "regular" | "bold" | "italic" | "boldItalic";

/** Supported font export formats. */
export type FontFormat = "ttf" | "otf" | "woff" | "ttc";

/** Presets for filtering targeted alphabets and character sets. */
export type CharacterPreset =
  | "ascii"
  | "latin"
  | "cyrillic"
  | "greek"
  | "arabic"
  | "hebrew"
  | "devanagari"
  | "thai"
  | "korean"
  | "japanese"
  | "chinese"
  | "symbols"
  | "all";



/** Typed inputs shared by the future asset and export stages. */
export interface FontGenerationOptions {
  readonly minecraftVersion: MinecraftVersion;
  readonly outputDirectory: string;
  readonly styles?: readonly FontStyle[];
  readonly formats?: readonly FontFormat[];
  readonly exclude?: readonly FontStyle[] | FontStyle | string | undefined;
}

function assertNonEmptyString(value: string, name: string): void {
  if (value.trim().length === 0) {
    throw new RangeError(`${name} must not be empty`);
  }
}

const VALID_STYLES = new Set<FontStyle>([
  "regular",
  "bold",
  "italic",
  "boldItalic",
]);
const VALID_FORMATS = new Set<FontFormat>(["ttf", "otf", "woff", "ttc"]);

function copyAndValidateList<T extends string>(
  values: readonly T[],
  validValues: ReadonlySet<T>,
  name: string,
): readonly T[] {
  const copy = [...values];
  if (new Set(copy).size !== copy.length) {
    throw new RangeError(`${name} must not contain duplicates`);
  }
  for (const value of copy) {
    if (!validValues.has(value)) {
      throw new RangeError(`${name} contains an unsupported value: ${value}`);
    }
  }
  return Object.freeze(copy);
}

/** Validates and copies generation options without performing I/O. */
export function createFontGenerationOptions(
  options: FontGenerationOptions,
): FontGenerationOptions {
  assertNonEmptyString(options.minecraftVersion, "minecraftVersion");
  assertNonEmptyString(options.outputDirectory, "outputDirectory");

  const result: {
    minecraftVersion: MinecraftVersion;
    outputDirectory: string;
    styles?: readonly FontStyle[];
    formats?: readonly FontFormat[];
  } = {
    minecraftVersion: options.minecraftVersion,
    outputDirectory: options.outputDirectory,
  };

  if (options.styles !== undefined) {
    result.styles = copyAndValidateList(
      options.styles,
      VALID_STYLES,
      "styles",
    );
  }
  if (options.formats !== undefined) {
    result.formats = copyAndValidateList(
      options.formats,
      VALID_FORMATS,
      "formats",
    );
  }

  return Object.freeze(result);
}

